create table
  public.potion_catalog (
    sku text not null,
    red_ml integer not null default 0,
    green_ml integer not null default 0,
    blue_ml integer not null default 0,
    quantity integer not null default 0,
    cost integer not null default 0,
    potion_id integer generated by default as identity,
    dark_ml integer not null default 0,
    constraint potion_catalog_pkey primary key (potion_id)
  ) tablespace pg_default;

create table
  public.global_inventory (
    num_red_ml integer null default 0,
    gold integer null default 100,
    num_blue_ml integer null default 0,
    num_green_ml integer null default 0,
    id integer generated by default as identity,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.carts (
    cart_id integer generated by default as identity,
    customer_name text not null,
    can_buy ? boolean null,
    constraint carts_pkey primary key (cart_id),
    constraint carts_cart_id_key unique (cart_id)
  ) tablespace pg_default;

create table
  public.cart_items (
    cart_id integer not null,
    potion_type text null,
    count_to_buy integer not null,
    constraint cart_items_pkey primary key (cart_id)
  ) tablespace pg_default;