create table
  public.barrel_ledger_entries (
    id bigint generated by default as identity,
    time_stamp timestamp with time zone not null default now(),
    red_ml_delta integer not null default 0,
    blue_ml_delta integer not null default 0,
    green_ml_delta integer not null default 0,
    dark_ml_delta integer not null default 0,
    constraint barrel_ledger_enteries_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart_items (
    cart_id integer not null,
    sku text null,
    count_to_buy integer not null,
    entry_id integer generated by default as identity,
    constraint cart_items_pkey primary key (entry_id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (cart_id)
  ) tablespace pg_default;

create table
  public.carts (
    cart_id integer generated by default as identity,
    customer_name text not null,
    constraint carts_pkey primary key (cart_id),
    constraint carts_cart_id_key unique (cart_id)
  ) tablespace pg_default;

create table
  public.carts (
    cart_id integer generated by default as identity,
    customer_name text not null,
    constraint carts_pkey primary key (cart_id),
    constraint carts_cart_id_key unique (cart_id)
  ) tablespace pg_default;

create table
  public.potion_catalog (
    sku text not null,
    red_ml integer not null default 0,
    green_ml integer not null default 0,
    blue_ml integer not null default 0,
    cost integer not null default 0,
    potion_id integer generated by default as identity,
    dark_ml integer not null default 0,
    constraint potion_catalog_pkey primary key (potion_id)
  ) tablespace pg_default;

create table
  public.potion_ledger_entries (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    quantity_delta integer not null,
    potion_id integer not null,
    constraint potion_ledger_enteries_pkey primary key (id),
    constraint potion_ledger_entries_potion_id_fkey foreign key (potion_id) references potion_catalog (potion_id)
  ) tablespace pg_default;